In [ ]:
# 전체 행 표기
pd.set_option('display.max_rows', None)

# 전체 행 표기 리셋
pd.reset_option('display.max_rows')

### 데이터 불러오기 및 EDA

In [121]:
import pandas as pd

df = pd.read_csv("C:/Users/User/Desktop/성범죄키워드/브런치.csv", encoding="utf-8")  # 인코딩은 원본 파일이 저장 됐을 때의 인코딩과 일치시키기기

df.head()

,No,Keyword,Volume,Position,Est. Visits,CPC,Paid Difficulty,SEO Difficulty,Ranking URL
0,1,법무법인,4400,57,9,₩9.55,22,20,https://brunch.co.kr/@3fd7d61eb3764fa/32
1,2,법무 법인,3600,72,9,₩4.26,45,15,https://brunch.co.kr/@3fd7d61eb3764fa/32
2,3,그루밍,4400,35,9,₩4.65,2,33,https://brunch.co.kr/@@6Y04/7
3,4,형사전문 변호사,1600,16,15,₩14.49,14,23,https://brunch.co.kr/@@ftB4/66
4,5,형사전문변호사,1600,25,8,₩14.49,14,1,https://brunch.co.kr/@@ftB4/66

### 경쟁사의 주요 트래픽을 책임지고 있는 키워드는?

1. 순위별 전환율을 구한다.
전환율(conversion_rate) =  Est. Visits / Volume * 100

2. 순위별 전환율 평균값을 확인한다.
ex)
1위 평균전환율 = 34%
2위 평균전환율 = 8%
3위 평균전환율 = 8%

3. 1~3위 키워드를 추출한다. 평균전환율 이상 조건을 걸어서

분석 목적:
경쟁사의 웹사이트에서 실제로 높은 트래픽과 전환을 발생시키는 핵심 키워드를 식별하여, 효과적인 콘텐츠 전략 수립에 활용하고자 합니다.

In [ ]:
# 트래픽이 높은 기준으로 키워드 정렬
    #  클릭률이 높다는 얘기이니니, 게시물 제목을 참고해 봐도 좋음
df.sort_values('Est. Visits', ascending=False)

In [ ]:
# 방문자 수 / 키워드 검색량 * 100 
df['conversion_rate'] = round(df['Est. Visits'] / df['Volume'] * 100, 2)
df.sort_values('conversion_rate', ascending=False)

In [110]:
# 전환율의 분포가 어느정도이지?
df['conversion_rate'].describe()

# 전환율 75% 이상인 키워드는?  
    # 75%에 해당하는 수치로 수정
# df['conversion_rate'] >= 14   
# df[df['conversion_rate'] >= 1].sort_values('conversion_rate', ascending=True)

count    100.000000
mean       1.712000
std        3.980287
min        0.000000
25%        0.210000
50%        0.380000
75%        1.885000
max       30.480000
Name: conversion_rate, dtype: float64

### 경쟁사가 노출 중인 키워드의 순위

In [117]:
df.groupby('Position').agg({
    'conversion_rate': 'mean',
    'Volume': 'mean',
    'Keyword': 'count'
}).round(2)

          conversion_rate   Volume  Keyword
Position
1                   35.01   695.00        2
3                   10.45   710.00        3
5                    5.38   433.33        3
6                    4.08   572.00        5
7                    3.15  1180.00        3
8                    1.88   480.00        1
9                    2.05   390.00        1
10                   1.19   590.00        1
11                   0.99   333.33        3
12                   1.15   260.00        1
13                   0.61   213.33        3
14                   0.90  1000.00        1
15                   0.50   300.00        2
16                   0.45   222.50        4
18                   0.40   755.00        2
19                   0.30  1000.00        1
20                   0.40   265.00        2
21                   0.19   293.33        3
22                   0.23   407.50        4
23                   0.28   960.00        2
24                   0.31   320.00        1
25                   0.16   265.00        2
26                   0.00   210.00        1
27                   0.14   465.00        2
29                   0.28   695.00        2
30                   0.21   335.00        4
32                   0.30  1000.00        1
33                   0.38   260.00        1
35                   0.13   300.00        2
36                   0.30  1000.00        1
37                   0.00   210.00        1
38                   0.31   320.00        2
40                   0.44  1600.00        1
41                   0.26  1150.00        2
42                   0.35  1300.00        2
43                   0.28   523.33        3
44                   0.26   390.00        1
47                   0.23  1300.00        1
48                   0.56  1890.00        2
51                   0.28   720.00        1
53                   0.38   260.00        1
55                   0.13   226.67        3
57                   0.00   210.00        1
60                   0.31   320.00        1
64                   0.21   480.00        1
69                   0.19   235.00        2
70                   0.21   480.00        1
71                   0.38   260.00        1
74                   0.34   290.00        2
76                   0.31   320.00        1
77                   0.31   320.00        1
81                   0.17   590.00        1
84                   0.20  1000.00        1
90                   0.17   590.00        1
93                   0.38   260.00        1
94                   0.17   590.00        1

### 미정의 분석방법

In [ ]:
# 조건에 맞는 1위 키워드 추출
position_1 = df[
    (df['Position'] == 1) & 
    (df['conversion_rate'] >= 34)  # 경쟁사의 순위별 평균 전환율 넣기기
]

# 조건에 맞는 2-3위 키워드 추출
position_2_3 = df[
    (df['Position'].isin([2, 3])) & 
    (df['conversion_rate'] >= 8)   # 경쟁사의 순위별 평균 전환율 넣기기
]

# 결과 합치기 및 정렬
target_keywords = pd.concat([position_1, position_2_3])
target_keywords = target_keywords.sort_values('Position')

# 결과 출력
target_keywords[['Keywords', 'Position', 'Volume', 'conversion_rate']]

In [ ]:
# 6위 이상의 키워드 중 전환율이 있는 키워드 추출 및 정렬
high_conversion = df[
    (df['Position'] >= 6) & 
    (df['conversion_rate'] > 0)
].sort_values('conversion_rate', ascending=False)

# 결과 확인 
high_conversion[['Keywords', 'Position', 'Volume', 'conversion_rate']]

In [ ]:
# 9-13위 키워드 추출
position_9_13 = df[
    df['Position'].between(9, 13)
].sort_values(['Position', 'Volume'], ascending=[True, False])

# 주요 지표와 함께 출력
position_9_13[['Keywords', 'Position', 'Volume', 'conversion_rate', 'Est. Visits']]

position_9_13[['Keywords', 'Position', 'Volume', 'conversion_rate', 'Est. Visits']].sort_values('conversion_rate', ascending=False)

### 데이터 시각화